name: libjson2builtvalue
description: Generates Dart built_value classes from given JSON. Based on https://github.com/charafau/json2builtvalue 
version: 0.1.0
homepage: https://github.com/glacion/libjson2builtvalue
author: Ahmetcan Guvendiren <ahm@glacion.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  recase: ^2.0.1
  tuple: ^1.0.1
  dart_style: ^1.2.7
  built_collection: ^4.2.0
  code_builder: ^3.2.0
